### ISSUE TITLE
How do I safely add environment variables?

### ISSUE THREAD

**Issue by mbifulco** [MicrosoftDocs/vsonline#100]
I'm trying to follow the instructions in [the advanced docs for `.devcontainer/devcontainer.json`](https://code.visualstudio.com/docs/remote/containers-advanced#_adding-environment-variables) for using environment variables in my projects.

**Purpose**
I'm building react web applicaitons that need API keys for things like segment/CMS - these keys need to be secure, and cannot be checked into source control.  For that reason, they're typically kept in a `.env` file in my local environment, or in some cases in my `~/.bash_profile`.

I'd like to use the process outlined in the link above to source environment variable values from a `.devcontainer/devcontainer.env` file when my VS Online environment is loaded.

My `.devcontainer/devcontainer.json` currently looks like this:

```json
{
  "runArgs": [
    "--env-file",
    "devcontainer.env"
  ]
}
```

But environment variables don't load.  I feel like I'm missing a step to force the online environment to actually load look at the configuration for the file, but that's just a hunch.  

Any help is appreciated!

**Comment by jkeech** [comment]
Do you need the environment variables loaded in the VS Code process itself (for extension to access), or just for things like terminals/tasks inside the editor? If the latter, then it's a bit easier today. There are a couple options:

1) [Configure a dotfiles repo](https://docs.microsoft.com/en-us/visualstudio/online/reference/personalizing) when creating the environment. This can be used to fetch secrets in some way and then update `~/.bashrc` so they are visible for each new bash shell, including new terminals that are spawned in VS Code. `~/.bash_profile` won't work because that is only executed for login shells.
2) Create a file `~/.env` which is a shell script that can set environment variables. If this file exists, it will be executed prior to starting the VS Code remote server. The only downside here is that if you are using a private repo, the repo won't be cloned until after the first connection is established, so the VS Code process will already be running before the `~/.env` file is created. Therefore you would have to Suspend and then resume the environment (or disconnect and wait >5 minutes for the VS Code server process to shut down) in order for VS Code itself to pick up the variables on restart. This approach is only needed if you want the variables visible from within the VS Code process/extensions. If you just need access from terminals or build tasks, then the `~/.bashrc` approach is simpler.

**Comment by mbifulco** [comment]
Ah, thanks! 

So, these environment variables are used strictly by the processes that run my dev/build environment (_not_ VS Code extensions, etc).  Sounds like I'm in luck

1. this isn't an option for this particular use case because these API keys shouldn't be checked into source control. `~/.bash_profile` is just a hack I use locally for repos that don't have easy support for `.env` files, and isn't a great characterization of the use case.  Sorry about the confusion there.

2. This sounds promising.  How do I create/edit `~/.env` in VS Online? From what I can tell, I won't see it in the IDE, so is my best option to edit/create it from the command line via VIM/nano/etc?  And will that file look like this?

  ```bash
  ENVIRONMENT_VARIABLE_1=lorem
  ```

  or this?
  ```bash
  export ENVIRONMENT_VARIABLE_2=ipsum
  ```

So far I haven't had luck getting `~/.env` to work 🤔

**Comment by mbifulco** [comment]
Any tips on this?

**Comment by jkeech** [comment]
Sorry for the delay. I wouldn't recommend the `~/.env` for your scenario actually -- it's not as nice as the   `~/.bashrc` file since it is only picked up after a VS Code server restart (such as environment suspend + resume). If you do choose to use `~/.env`, you should treat it as a normal shell script, e.g. `export ENVIRONMENT_VARIABLE=value`

In either case, you'll need to figure out a good way to populate the file with your secrets. We don't have a great solution to that today. We are tracking the broader issue of secrets management in #50. We do bundle the `az` cli in the base image now, so if you have secrets stored in Azure Key Vault, you could manually login and pull the secret from KV and then place the value in the file on disk.

Both `~/.bashrc` and `~/.env` are outside of the workspace directory and would not typically be checked in to source control.

**Comment by lostintangent** [comment]
You can now set environment variables in your devcontainer.json file, using either the “containerEnv” or “remoteEnv” properties. You can find more info on that here: https://code.visualstudio.com/docs/remote/containers#_devcontainerjson-reference. I’m going to close this as resolved, but please let us know if you run into any issues or feedback 👍 In addition, we’ll use #50 to track the overall secrets management experience. Thanks!
