### ISSUE TITLE
VS Online cannot open for non-subscription owners

### ISSUE THREAD

**Issue by blowdart** [MicrosoftDocs/vsonline#104]
Due to security my main AAD user is neither an admin or subscription own in Azure. When I signin with that user I cannot see any environments,

![Annotation 2019-11-06 135546](https://user-images.githubusercontent.com/796298/68341367-26db6780-009d-11ea-83f6-d44df3caefeb.jpg)

And create new plan doesn't see any subscriptions

![Annotation 2019-11-06 135137](https://user-images.githubusercontent.com/796298/68341099-913fd800-009c-11ea-9574-1acce0610196.jpg)

That's probably to be expected, although better messaging that says "You cannot create a VS Online plan" would be better than having a drop down with no subscriptions.

I logged in as my admin user and could create an environment happily enough, 

![Annotation 2019-11-06 135320](https://user-images.githubusercontent.com/796298/68341212-d6fca080-009c-11ea-9791-383efed213fd.jpg)

but that leaves me stuck. I don't want to run as my admin user, or grant my normal user the ability to administer a subscription, but I do want to use environments as the normal user. Basically I need a way to either

a) Delegate permissions just for VS Online environment creation to a non-admin user _or, less preferably_
b) Have non-admin users see environments created at a subscription level.

Either way, principle of least privilege is desired.

**Comment by jkeech** [comment]
You should not need to be a subscription owner to create a VS Online plan in Azure, but you do need to have at least Contributor permissions in order to

1) Register the `Microsoft.VSOnline` resource provider in your subscription
2) Create the plan resource

Your admin account (or any account with sufficient privileges on the subscription) could do step 1, but step 2 currently has to be done by the same identity that intends to create and use environments. Today, plans are single-user, so the person who creates the plan is the only one who can create and view environments in that plan. We do intend to provide more team features for sharing plans with true RBAC support in the future.

I think the most scoped-down approach for now would be to have your admin account first register the resource provider, which happens automatically when you create the first plan in a given subscription, and then grant your other account Contributor permissions within a specific Resource Group that you create in that subscription just for the VSO plan. You other account can then sign into VSO and create a plan, and in the Advanced section, specify the resource group that it has Contributor permissions on. From there, you can create and use environments in that plan. You could even remove Contributor permissions for that account from the subscription after you've created the plan,, but the plan resource itself needs to remain. Deleting the plan will delete all of the contained environments.

Let me know if that solves your problem. Thanks!

**Comment by blowdart** [comment]
Yup that works :)
