### ISSUE TITLE
Doesn't work together with Remote - SSH extension

### ISSUE THREAD

**Issue by Niek** [MicrosoftDocs/vsonline#113]
I'm trying to connect to my remote (headless) server with the "Remote - SSH" extension (nightly version) and install the "VS Online" extension in order to run a self-hosted environment, by following this documentation: https://docs.microsoft.com/en-us/visualstudio/online/how-to/vscode#self-hosted

The "VS Online" extension can't seem to be installed on a SSH instance, but the "Azure Account" extension can be installed without issues. When I connect to the SSH instance and choose "VS Online: Register Local Environment" from the command palette, I get the error: "Failed to register local environment: Install the Azure Account extension.". This is strange, since the "Azure Account" extension is definitely installed and logged in, for example when running "Azure: Select Subscriptions" I see the subscriptions list.

Am I missing something? Or is this flow simply not possible yet, and are only graphical self-hosted installations possible right now? I see some other people experiences the same issue: https://news.ycombinator.com/item?id=21447301

**Comment by taiyosogawa** [comment]
@Niek thanks for asking and sorry for the less-than-ideal experience. Unfortunately, registering a remote development environment (SSH, WSL, etc.) is not currently supported. I just created a consolidated tracking issue #116 because we have seen this happen a few times. We'd love to continue the conversation over there.

In the meantime, we are deploying an improvement to the error messaging to make things a bit clearer.
