### ISSUE TITLE
Cannot run "register local environment" command on a remote connected server.

### ISSUE THREAD

**Issue by windoze** [MicrosoftDocs/vsonline#155]
When I ran "VS Online: register local enviroment" command from VSCode command paletter when it connected to a remote server":

1. The "starting folder" selection box listed local directories instead of directories on the remote server.
2. After I input some directory in the input box, it then popped up another error message "Failed to register local environment: Install the Azure Account extension." But this extension is installed and configured, I can see my Azure resources.

The only working usage of the command is to register from the computer where VSCode is locally installed, but neither WSL or Remote SSH worked.

What I expected is to register my self-hosted headless server as a self-hosted environment, then I can connected from online.visualstudio.com with a browser, as iPad still doesn't have a native VSCode right now.

**Comment by taiyosogawa** [comment]
@windoze thank you very much for reporting this bug and sorry about the non-ideal experience registering the remote server as a self-hosted environment. 

Currently, registering a local environment while connected to a remote server (WSL or SSH) is not supported, but we have received a lot of interest, which we are tracking on #116.

In your case, you might also be interested in #69, which is tracking a feature to enable registering an environment via command line.

In the meantime, we've improved the messaging to prevent the confusing "Install the Azure extension" notification, which will be be rolled out in the extension shortly.

Hopefully this points you to all the relevant existing issues, so I'll close this issue, but let us know otherwise.
