### ISSUE TITLE
Ability to configure keybindings on environment creation.

### ISSUE THREAD

**Issue by asw101** [MicrosoftDocs/vsonline#158]
Is there any way to configure keybindings upon environment creation?

I can't seem to be able to to overwrite `keybindings.json` as part of my `postCreateCommand` (https://docs.microsoft.com/en-us/visualstudio/online/reference/configuring ). And I don't _think_ I can do it via the `Dotfiles Repository` (https://docs.microsoft.com/en-us/visualstudio/online/reference/personalizing ).

My use case is I would like to be able to have people run environments that have default keybindings for commands such as `workbench.action.terminal.runSelectedText`.

**Comment by lostintangent** [comment]
@asw101 Hey! What do you think about just putting a `.vscode/keybindings.json` file in your project's repo? In general, when config is meant to be carried with the repo, and not the individual, we're trying to enable it to be checked into the codebase. That way, even if folks aren't using VS Online, they'd get the same behavior when using VS Code.

**Comment by asw101** [comment]
@lostintangent I think that would be ideal!

At this stage been putting everything from settings to bash scripts under `.devcontainer/`. I saw my settings can live inside `.devcontainer/settings.json` which was helpful. I find this more useful than Dotfiles at the moment.

I tried putting my [keybindings.json](https://github.com/asw101/hello-vso/blob/master/.devcontainer/keybindings.json) under `.devcontainer/`, so I could overwrite them via `postCreateCommand` but the path to global file is shown as `/User/keybindings.json` which is not accessible. Project-level keybindings would be very helpful here.

**Comment by lostintangent** [comment]
@egamma @chuxel Thoughts on this?

**Comment by Chuxel** [comment]
@asw101 Yeah, there's a feature request for VS Code itself here that we may want to close this issue in favor of (since that's where the change would be made): https://github.com/microsoft/vscode/issues/23757 and this is the historic PoV on it: https://github.com/microsoft/vscode/issues/10708#issuecomment-241330047

The `devcontainer.json` includes a `settings` property that will be used as machine level settings for the Remote - Containers extension.  This is not yet supported in VSO (though it should be very soon) - You don't even need to use a postCreateCommand for that once support is in place. The reason this exists is to handle things like paths to SDKs (e.g. java.home) that do vary from machine to machine and container to container.  

Love to understand the specific scenario here to better understand the right recommendation. For classes / education, I wouldn't recommend changing defaults unless the bindings are published in extension so users can continue to use them on their own in different projects. For other scenarios, a user level sync seems to be more powerful.

**Comment by egamma** [comment]
As @chuxel pointed out above, this has been discussed. This comment https://github.com/microsoft/vscode/issues/4504#issuecomment-199359339 captures the current thinking. 

The scenario from @asw101 above

>My use case is I would like to be able to have people run environments that have default keybindings for commands such as workbench.action.terminal.runSelectedText.

Sounds like a custom keymap. Custom keymaps are done as [extensions](https://marketplace.visualstudio.com/search?target=VSCode&category=Keymaps&sortBy=Installs). Once you have an extension, then you can include it in the devcontainer.json and it will be active for these environments.

**Comment by asw101** [comment]
Thank you for your insights, @egamma and @Chuxel! 

I had missed that settings in `devcontainer.json` were not being used. Thank you for clarifying.

I use keybindings for simple things like `workbench.action.closeActiveEditor` and `workbench.action.files.newUntitledFile` and bind them to `Ctrl+W` and `Ctrl+N` respectively because the default `Cmd+W` and `Cmd+N` clash with Chrome on macOS in VS Online. I also bind `workbench.action.terminal.runSelectedText` to `Ctrl+Shift+Z` to provide a "bash REPL" experience via the integrated terminal.

Thank you for the pointer regarding extensions. I thought this process would be more involved, but after browsing the [docs](https://code.visualstudio.com/api/get-started/your-first-extension) I created a keymap extension (which also my first code extension) and it was relatively straightforward. The `yo code` > `What type of extension do you want to create?` > `New Keymap` scaffolding was particularly helpful.

**Comment by egamma** [comment]
@asw101 nice 👍 and glad you have found the docs useful.

**Comment by lostintangent** [comment]
Per the recommendation above, I’m going to close this issue as resolved. Let us know if the keymap solution isn’t sufficient, and please feel free to reopen this issue for further discussion. Thanks!
