### ISSUE TITLE
Not clear in example that feature flag needs to be on for dockerFile to work

### ISSUE THREAD

**Issue by scycer** [MicrosoftDocs/vsonline#170]
Took me a while of fiddling until I stumbled upon the part that says the customContainers experimental feature flag needs to be on. 

The example JSON however has the dockerfile specified but without the feature flag aswell so it was not clear why it wasnt working nor did any errors show when loading up the vs online environment.

https://docs.microsoft.com/en-us/visualstudio/online/reference/configuring#visual-studio-online-configuration-sample

**Comment by lostintangent** [comment]
That was actually a doc bug, since we haven't officially shipped custom Dockerfile support yet. I just removed this sample from the doc you mentioned, so I'm going to close this issue for now. We'll make sure to let folks know when Dockerfile support is ready, but in the meantime, the experimental feature flag wasn't meant to be publicly documented/consumed. Thanks!

**Comment by scycer** [comment]
That's fair enough but why do the docs still say u can specify the docker file if it's not actually going to work? And even though the feature flag wasn't to be documented will it still work for now? (noting it may have issues while its experimental)
