### ISSUE TITLE
Self-hosted environments don’t inherit extensions from the host machine

### ISSUE THREAD

**Issue by sethamclean** [MicrosoftDocs/vsonline#230]
Despite the live share plugin being installed on the system hosting the environment no live share options are available and the plugin is listed as not being installed. Is this a limitation of self hosted environments? Is this and other possible limitations documented some where?

**Comment by lostintangent** [comment]
When you register a self-hosted environment, it’s actually spinning up an isolated instance of the VS Code server, which doesn’t currently inherit any of the extensions that are already installed on the host machine. Since you’re registering the environment from within VS Code, I realize that this isn’t the most intuitive behavior. So we’ll use this bug to track improving this experience 😁

Out of curiosity: would you expect/want all extensions that are installed on the host machine to also be installed in the self-hosted environment? I’m assuming so, but I just wanted to double-check.

In the meantime, when you connect to the self-hosted environment, you should be able to install the Live Share extension within it from the extensions tab. Let us know if that doesn’t work 👍

**Comment by sethamclean** [comment]
That's great info thank you! That explains a lot. Unfortunately this is being exacerbated by another issue I have with vscode. I'm unable to get vscode to recognize my organizations custom certs. I've installed the existing plugins by manually curling the files down and using the cmd line interface to install them. Unfortunately I have no idea how to tell the cmd line to install into the isolated instance. Does the isolated instance have its own cli?

Thanks again!

**Comment by sethamclean** [comment]
I found the isolated environment in my home folder under ~/.vscode-remote I copied my plugins folder into the plugins folder there and they all appear to be working now. Thanks again for the info.

**Comment by taiyosogawa** [comment]
Sorry we didn't get back to your last comment sooner @sethamclean. I'll close this since it sounds like the issue has been resolved, but feel free to reach out again!
