### ISSUE TITLE
Live Share in the browser

### ISSUE THREAD

**Issue by nbarkhina** [MicrosoftDocs/vsonline#325]
When launching a Live Share is there any plans to allow the invitees to be able to join via a browser session as well? so that they don't need to install VS Code. Would be a very handy feature I think to quickly get a Live Share going with no requirements other than a browser

**Comment by lostintangent** [comment]
@nbarkhina Hey! We are working on this exact thing at the moment, and hope to have something to share soon 👍 Out of curiosity: what use case/scenario would you see yourself using Live Share for? I just ask since you mentioned your invited guests wouldn't have VS Code installed, and I'd love to learn more about that.

**Comment by nbarkhina** [comment]
Great to hear thanks! One big use case I can think of is if we need to interview a candidate for a position, would make for a really great low-friction experience to get them into a known environment and watch as they code.  But also more generally I think it would improve the accessibility of Live Share if as another example you needed help with your code and you could just send someone a hyperlink without worrying about what machine they are currently on.

**Comment by lostintangent** [comment]
OK cool, thanks so much. Interviews is actually one of the key use cases we’re building this for, so I appreciate the additional feedback 😁
