### ISSUE TITLE
Allow devcontainer.json to specify a docker compose file

### ISSUE THREAD

**Issue by srivatsn** [MicrosoftDocs/vsonline#35]
To be able to customize an environment such that repos with multiple services can be easily initialized.

**Comment by Uili-Simteau** [comment]
Any update on this issue?

**Comment by jkeech** [comment]
@Uili-Simteau, we now support docker inside of environments, but we do not currently have a way to declaratively specify that extra containers should be created/started when you create the environment. You can manually create containers from within the environment though.

**Comment by YoungElPaso** [comment]
Is there an upper limit to the number of services/containers running? I thought I read in the docs that only 1 service could be run at once?

I have an application that uses about 5 services; if the implication of the last comment is simply that I have to manually start them, that's great, I can handle that.  For instance, I have a main 'app' service, a linter, an optional caching service, required db and lastly a testing service which I'd like to use periodically.  These are already in my docker-compose but not all need to be run by default.

I must admit, I don't quite understand the limits of VS Codespaces vs Azure devops... I would certainly love to be able to use VS CS as the single solution.

**Comment by lostintangent** [comment]
@YoungElPaso I don’t believe we enforce a limit on the number of services your Docker compose file can include. Though @edgonmsft can confirm. The comment in the docs about 1 service, is referring to the fact that you can only connect VS Code itself to one of the service containers. Though all the other service containers can still run as “siblings” of the main service you’re developing in. If you’re running into any issues with this workflow, please let us know!

In the meantime, I’m going to close this issue, since we shipped support for Docker compose 👍
