### ISSUE TITLE
VSCode Online in browsers on ARM platforms timing out - is this expected?

### ISSUE THREAD

**Issue by contention** [MicrosoftDocs/vsonline#414]
This may be related to #395, and I'm aware that there isn't an official build of VSCode for ARM platforms.

However, I'm trying to connect to a self-hosted headless environment (a DigitalOcean droplet) via VSCode Online in the default Chromium browser on the latest Raspbian... and it times out without connecting.

I can successfully connect to this environment via browsers on other platforms (MacOS and iPadOS), and I can connect using desktop VSCode and the Online Extension on MacOS, so there doesn't appear to be a problem with the environment itself.

I'm just wondering if this is expected behaviour in browsers on ARM platforms? I was hoping that VSCode Online would be a pretty neat workaround to not being able to use VSCode Desktop on the Pi.

Thanks.

**Comment by taiyosogawa** [comment]
Hi @contention, thanks for reaching out.

When connecting to an environment via the browser, there is a timeout limitation imposed that does not apply when connecting via another instance of VSCode. Based on your description, my guess is that is what is happening.

Does it take a long time to connect via VSCode? Roughly how long is the connection time? Note: the connection time may differ depending on how many times you have connected before.

If you haven't already:
After connecting with the browser fails, try waiting a few minutes then connecting with the same browser. Even though the first connection failed, the agent on your host environment should still be caching dependencies. The exact dependencies is determined by the client you connect with, which is why you will experience a cold hit the first time you connect (on most platforms, we are still able to set up within the timeout even on a cold hit).

**Comment by contention** [comment]
Thanks for the quick response.

So, connecting to this environment via Desktop VSCode on MacOS takes a few seconds. All works great. Similarly, connecting to this environment via browser VSCode in Safari on MacOS is quick too.

The problem is when I try to connect via browser VSCode in Chromium on a Raspberry Pi. I've tried to connect this way a few times now, with up to 30 minutes between attempts, and also making sure no other clients are connected to the environment.

I see the same error every time:

`Failed to connect to the remote extension host server (Error: Time limit reached)`

So no extensions are loading, etc, etc.

I just wondered whether this was something to do with it being an ARM machine, although I'd expected it to work with it being browser based rather than native, if that makes sense?

**Comment by jkeech** [comment]
I believe VS Code has a 20 second (or maybe 60 seconds?) timeout on the initial connection. It's possible that the Raspberry Pi hardware is not fast enough to finish establishing the connection within that timeframe. This is a scenario where it might benefit from VS Code having a longer timeout (or configurable timeout). @srivatsn @kieferrm

**Comment by taiyosogawa** [comment]
Yes, the timeout via the browser is currently 20 seconds. 

@jkeech, do you know if we have an open issue/request with VSCode to increase that limit?

**Comment by jkeech** [comment]
@taiyosogawa, looks like you filed https://github.com/microsoft/vscode/issues/86202 back in December.

**Comment by taiyosogawa** [comment]
@jkeech, your searching skills are extraordinary and my memory is not! 

@contention, if it's okay, I'll close this issue in favor of the other one. Thanks again for reaching out and don't hesitate to file additional questions.
