### ISSUE TITLE
Rust RLS VS Extension: dependencies don’t install correctly

### ISSUE THREAD

**Issue by clarkezone** [MicrosoftDocs/vsonline#46]
I’m attempting to do rust development using VS online.  The problem is that the RLS extension which makes intellisense and other rust features work doesn’t install the needed dependencies and thus doesn’t work correctly.

The extension installs ok.  I have installed cargo and rustup in the VM and updated the .bashrc so those are both on the path.  When i then open a .rs file in the editor, I see **Rust Tools Missing** in the status bar.  Normally, clicking on that causes the extension to install the missing tools using cargo.  In VS Online, clicking on that button starts a new bash shell but doesn’t trigger the dependency install.  If I open a bash prompt, i can marnually run cargo but since there are many dependencies for RLS and I don’t know the complete list, I’ve been unable to manually install them and get RLS running.

**Comment by lostintangent** [comment]
@clarkezone Thanks for reaching out! We'll look into this this week and see what might be going on. We definitely want to enable Rust development, and so we can hopefully unblock this ASAP. Stay tuned!

**Comment by bnb** [comment]
I tried testing this myself and got it working after facing a similar problem yesterday with a different extension. I got the RLS extension working by suspending/unsuspending the environment once everything was set up appropriately (i.e. extension installed, clicked "reload required", rustup installed). 

You can see the exact steps I took in https://github.com/MicrosoftDocs/vsonline/issues/95 @clarkezone ❤️

**Comment by jkeech** [comment]
I'm going to consider this issue resolved since the recommended path going forward is to use a custom image with devcontainer.json for environment variables that need to be set prior to the VS Code Server process launching: #15.

**Comment by bnb** [comment]
@jkeech does that mean that the actual underlying problem requiring a suspension/unsuspension was solved?

**Comment by jkeech** [comment]
There's no real fix for that since you can't update the environment variables for the running process after it is running. But there are a couple workarounds:

1) Recommended: Configure the environment to have the environment variable pre-set before the VS Code Server launches (custom image/Dockerfile or environment specified in devcontainer.json).
2) We are going to be providing a command in the extension to kill the VS Code Server process. This is sort of like a soft-suspend/reboot. It will kick you out because the connection will drop, but then it should reconnect automatically and spin the new server back up. So if you had modified environment variables in a way that the VS Code Server process would pick them up, the newly spun up server would reflect that.

**Comment by bnb** [comment]
Really glad to hear that both of those workarounds exist/will exist!

Would it be at all possible to push folks toward running that command when an extension executes an operation that would need it? i.e. a toast saying something along the lines of "You may want to run `$COMMAND` to reboot the VS Code server."

**Comment by jkeech** [comment]
Hmm. I'm not sure how we would be able to capture/inspect commands that are setting environment variables. Maybe we could have a file watcher that looks at things like the bash profile, but would need to think on it some more.

**Comment by bnb** [comment]
Perhaps this is also solvable from the Extension maintainer or marketplace side? e.g. I assume Language Server extensions will always have this problem.
