### ISSUE TITLE
Azure Machine Learning and Azure Ansible dev containers fail to display folders after starting

### ISSUE THREAD

**Issue by Chuxel** [MicrosoftDocs/vsonline#469]
The Azure Machine Learning and Azure Ansible dev containers are able to successfully build and a Codespace is created, but once you get into the environment, the folders do not load. 

This might be because of #459 since these do use the docker socket, but the way it is failing is different.

Repro:
Open one of these repos in a Codspace
- Azure ML: https://github.com/Chuxel/codespace-test4
- Azure Ansible: https://github.com/Chuxel/codespace-test3

I was not able to directly observe what the problem was.

//cc: @edgonmsft

**Comment by edgonmsft** [comment]
I just tried this 2 repositories and they worked for me. I think you got a rare issue where the vscode server didn't start and that's why you didn't see any folders?

At this point in time both work fine since we mount the docker socker by default, when I remove that I'll add mounting support for devcontainer.json to conserve the functionality. 

Am I missing something you expected inside the environment?

**Comment by Chuxel** [comment]
@edgonmsft Did you try in GH Codespaces or VS?  Let me see if it happens in VS Codespaces, I'd been using GH.

**Comment by edgonmsft** [comment]
Gotcha I did it from desktop. Let me try too.

**Comment by jkeech** [comment]
@chuxel, I just tried both in Codespaces in GH, and they worked. I did get some timeouts on first try spinning up the remote server process, maybe due to the number/size of pre-installed extensions taking longer than the 20 second timeout in VS Code. But on refresh they both worked.

**Comment by Chuxel** [comment]
@jkeech  @edgonmsft Thanks for checking... odd. Well, glad it is working on your end... this could be something with my setup or account I suppose.  I'll close for now given that and reopen if I figure out a repro.
