### ISSUE TITLE
"Failed to connect to the remote extension host server"

### ISSUE THREAD

**Issue by avdi** [MicrosoftDocs/vsonline#489]
It got as far as opening the online VS Code, but it seems to be having some trouble starting the server... 
![image](https://user-images.githubusercontent.com/982/81481024-d7fcbf00-91f2-11ea-8888-214a820c1a45.png)

Repo is public here: https://github.com/gracefuldev/sixmilebridge.git

_Originally posted by @avdi in https://github.com/MicrosoftDocs/vsonline/issues/479#issuecomment-626211748_

**Comment by edgonmsft** [comment]
Hi Avdi!

I just tried your repo and its related to a limitation we currently have with how we are running docker-compose.

We currently only support version 3 for the docker-compose files but I'm actively working on converting that limitation so that its just needs to be that version or above.

We are tracking that particular issue on this one:

https://github.com/MicrosoftDocs/vsonline/issues/457

I'm going to close this one and we can follow this particular change there.

Thanks!
