### ISSUE TITLE
Secret management

### ISSUE THREAD

**Issue by nathansoz** [MicrosoftDocs/vsonline#50]
It would be awesome if there was a zero touch or light touch way for environments to have per-user secrets. 

For example, our project has both blob storage and cosmos db dependencies. For blob storage, it makes a lot of sense for the environment to set up azurite (azure storage emulator on linux). For CosmosDB however, we will need to use real cosmos (there is no cosmos db emulator support on linux). Obviously we don't want to check that type of secret in to source control, and if configurations are meant to be shared between dev teams it may be that we want such secrets to be per-user.

Idea 1: Have environment integration with keyvault. Ideally I could specify a global keyvault that all of my environments can use and then secrets can propagate to the environment. 

Idea 2: Allow prompting the user for said secrets as part of workspace initialization. This could also be a fallback for when keyvault isn't configured.

Idea 3: Make an extensible secret provider and provide a couple of drop in ones (keyvault, interactive) 😊

**Comment by lostintangent** [comment]
@nathansoz Yeah this is definitely something we need to explore. "Roaming" secrets is a key gap in our E2E right now, and so we hope to address that in the coming months. We'll use this issue to discuss design ideas 👍

**Comment by jasongin** [comment]
I've been doing some investigation into secret management for VS Online environments. Feedback on these ideas is welcome!

Ideally, I think there should be solutions and/or best practices for handling all the following kinds of secrets in VS Online:
 1. **Git HTTPS credentials**
 1. **SSH private keys** - especially for use with git SSH authentication
 1. **GPG private keys** - especially for use with git commit signing
 1. **Developer secrets** - credentials, tokens, or other secrets typically stored in the OS secure keychain, often for use with various 3rd-party services, and especially with VS Code extensions that use the `keytar` interface.
 1. **Application secrets** - strings or files excluded from source control but referenced by code at build time or run time, including things such as API keys, storage keys, and private certificates. They're typically stored in environment variables or files.

VS Online currently has some partial solutions for a couple of these, though they only work with the VS Code desktop extension, not the browser experience:
 - A git credential helper in the environment forwards HTTPS credential requests to git on the client system. Often if credentials are already cached on the client this enables git HTTPS authentication to silently succeed.
 - The VS Code server has a `keytar` shim that forwards credential requests to the VS Code desktop client, which then invokes the local `keytar`.

Hypothetically, the same technique of forwarding secret requests to the client could be applied to SSH and GPG, because both of those support agent protocols (`ssh-agent` and `gpg-agent` respectively) that VS Online could plug into. That may have value for some scenarios. However, this technique generally cannot work using the browser client because there is no local `git` or `ssh` or `gpg` or `keytar` on the client to answer credential requests. While it could be possible to store secrets in browser local storage (with encryption), that would seem to be of limited benefit because a major promise of VS Online is that you can access environments from a browser on (nearly) any device, therefore secrets should be expected to "roam" along with you.

So this points toward a cloud storage solution for secrets, which in the Azure ecosystem naturally would be Azure Key Vault (as already suggested by the OP). I think it should be possible, with some work, to make most of the kinds of secrets listed above backed by a Key Vault:
 - **Git HTTPS credentials** - A credential helper (likely [GCM](https://github.com/Microsoft/Git-Credential-Manager-for-Windows/wiki/How-the-Git-Credential-Managers-works) or an improved version of it) can be developed that uses Key Vault for storage.
 - **SSH private keys** and **GPG private keys** - [ssh-agent](https://www.ssh.com/ssh/agent) and [gpg-agent](https://www.gnupg.org/documentation/manuals/gnupg/Invoking-GPG_002dAGENT.html) implementations can be developed that are backed by a Key Vault.
 - **Developer secrets** - An alternate `keytar` shim for VS Code extensions could be developed to store secrets in a Key Vault. (Is there any need to reroute OS keychain APIs at a lower level to support applications in the environment other than VS Code extensions? I don't know how feasible that would be.)
 - **Application secrets** - While there's no interceptable protocol like with the other kinds of secrets, the convenient thing about these is they're normally read-only, at least from the application perspective. (Updating them is typically a manual process.) So we only have to worry about retrieving them from a Key Vault into the environment. It seems like what's needed is a way to configure VS Online to automatically load a subset of Key Vault secrets into environment variables and/or files when starting up an environment.

Should the Key Vault resource be entirely managed by VS Online, or is a resource in the user subscription? I'd lean toward the latter because users should be in complete control of their own secrets, although that would result in some (very small) [additional costs](https://azure.microsoft.com/en-us/pricing/details/key-vault/).

**Comment by nathansoz** [comment]
`Should the Key Vault resource be entirely managed by VS Online, or is it a resource in the user subscription? `

Both? Ideally for a user on a given plan there could be one or more vaults. Maybe have a "create keyvault" helper gesture in the UI but also do allow BYO.

**Comment by jkeech** [comment]
Secrets support is now available in Codespaces! 🚀 🎉  You can configure secrets from the web portal in https://online.visualstudio.com/settings. These will be surfaced as environment variables inside the Codespace. Other secrets types such as files will be coming in the future.

Secrets have a concept of a filter that can be applied which can scope the secrets to apply to all Codespaces in your plan, or just ones that match a specific repository, or even down to a single Codespace, depending on where you want the secret to apply. The default (with no filter) is to have the secret applied to all of your Codespaces in the plan. Documentation for secrets will be coming soon. 

![image](https://user-images.githubusercontent.com/746020/86205636-383b1d80-bb1f-11ea-81bd-3cc03ed950e8.png)

![image](https://user-images.githubusercontent.com/746020/86205746-83edc700-bb1f-11ea-8e08-d5a3dc705ac7.png)
