### ISSUE TITLE
Make the Python Microsoft Language Server the default experience in VS Codespaces

### ISSUE THREAD

**Issue by luabud** [MicrosoftDocs/vsonline#549]
Hey there! I'm a PM working on the Python extension for VS Code, and the extension supports two IntelliSense engines: jedi (which is a 3rd party one and the current default experience for our users) and the Microsoft Python Language Server (MPLS). IntelliCode for Python depends on MPLS, so every time a user installs the Python extension, they'll see a notification prompt from IntelliCode asking to flip the language server engine (from jedi to MPLS), and then the Python extension requires the window to be reloaded to start MPLS. 

That said, because VS Codespaces installs IntelliCode by default (or at least that's what I noticed), it'd be awesome if it could also set an internal User setting to define the Python language server to be MPLS (`python.languageServer`: `"Microsoft"`). That way users don't have to reload twice (one after installing the Python extension, and then again to use MPLS).  Would that be possible? 

Thanks! 😊

**Comment by jkeech** [comment]
Hey @luabud, the best way to enable this is actually to have the Python extension change the behavior of which LS is selected by default. I could imagine two potential ways this is implemented:

1) Check specifically if you are running in a Codespace. #545 will make this really easy by providing an environment variable to check. If you are in a Codespace, default to MPLS instead of jedi.
    ```ts
    if (process.env.CODESPACES) {
      // switch to MPLS
    }
    ```
2) Since the desire for MPLS to be enabled seems to be more tightly coupled with IntelliCode, it might make more sense to check whether the IntelliCode extension is installed along with the Python extension and change the default behavior in Python if IntelliCode is present. This will make the experience better for users outside of Codespaces as well, and also has the benefit of keeping Codespaces and non-Codespaces behavior the same. This will minimize issues where something works on the desktop outside of Codespaces, but fails when they try it in a Codespace.
    ```ts
    if (vscode.extensions.getExtension("VisualStudioExptTeam.vscodeintellicode")) {
      // switch to MPLS
    }
    ```

(2) sounds like the best option to me since it keeps the behavior consistent inside and outside of Codespaces and makes the scenario work better for all VS Code users who use Python and IntelliCode

**Comment by luabud** [comment]
This is great info, thank you! 😊
