### ISSUE TITLE
Default Image fails to execute with a volume

### ISSUE THREAD

**Issue by qgerome** [MicrosoftDocs/vsonline#565]
Hello,

I don't know if it's PEBCAK or a real bug (or even a limitation) but I encounter a problem when I try to launch a docker image using docker-compose.

I created a test codespace env (default image, small vm).
I installed docker-compose using `pip install docker-compose`
Then I created 2 files :

*docker-compose.yml*
```docker
version: "3.8"
  services:
    test:
      image: node:latest
      volumes:
        - .:/app
      working_dair: /app
      command: bash -c "node ./index.js"
```
*index.js*
```javascript
console.log('Hello World')
```

If I run the command `docker-compose -f docker-compose.yml test` on the codespace, it will fail with this error:
<img width="652" alt="image" src="https://user-images.githubusercontent.com/1607549/83917824-d255b300-a777-11ea-9e7a-9a858dc72f1f.png">

BUT if I run it on my desktop, I don't have any error and it displays 'Hello World'

Is there something that I misconfigured or is there really a bug ?

Thanks for the help ❤️

**Comment by jkeech** [comment]
Our documentation is a bit lacking here, but let me try to explain what is going on. When you create a Codespace, a docker container is spun up on a host VM. Your app's source code is inside your main Codespace container at some path, but it's not in the host VM at that same path (even though it is on the host VM and bind mounted into the main container). The default image in Codespaces follows the [docker-outside-of-docker model](http://blog.teracy.com/2017/09/11/how-to-use-docker-in-docker-dind-and-docker-outside-of-docker-dood-for-local-ci-testing/) where the host's docker socket is bind mounted into the container. When you execute `docker` commands (or `docker-compose` commands), you are actually running `docker` on the host VM, manipulating sibling containers to your main application container. Paths that you provide in the `docker-compose.yml` are therefore relative to the host VM, not your Codespace container.

In short, you end up spinning up a sibling container that mounts a path from the host VM. There are a couple ways around this to do what you want:

1) The simplest is probably to define a `devcontainer.json` that builds your docker-compose app from the beginning. That would actually be running from a clone of your repo on the host, so the context would work correctly.
2) A more fragile way would be to continue to spin up the docker-compose container at runtime from inside of your Codespace, but to use the path of the repo from the host. This requires you to know where it exists on the host, which is not documented and is likely to change in the future. But for now you could hardcode it to `/var/lib/docker/vsonlinemount/workspace` for an empty Codespace or `/var/lib/docker/vsonlinemount/{repoName}` if you started with a repo.

I was able to get your sample working after fixing a couple typos/indentation issues and switching the volume mount to be using the hardcoded path on the host instead of the container's path:

```
version: "3.8"
services:
  test:
    image: node:latest
    volumes:
      - /var/lib/docker/vsonlinemount/workspace:/app
    working_dir: /app
    command: bash -c "node ./index.js"
```
![image](https://user-images.githubusercontent.com/746020/83927524-07471300-a742-11ea-9776-411c08c10f24.png)

**Comment by qgerome** [comment]
Thank you @jkeech for your answer ! I'll try with the `devcontainer.json` file 😊

**Comment by Vbubblery** [comment]
@qgerome Hello, does the `devcontainer.json` works for you?

How do you define the `devcontainer.json` file?

**Comment by qgerome** [comment]
> @qgerome Hello, does the `devcontainer.json` works for you?
> 
> How do you define the `devcontainer.json` file?

Argh, apparently I deleted the project :/
