### ISSUE TITLE
Cannot create a codespace  in Visual Studio 2019 proeview

### ISSUE THREAD

**Issue by PNicolle** [MicrosoftDocs/vsonline#573]
I would like to experiment codespace in Visual Studio Private Preview 2019, but I’m not able to create a codespace: 
-	The Instance Type combo is empty 
-	The Create and Connect buttons are disabled

![codespace](https://user-images.githubusercontent.com/66674499/84137260-bb9bae80-aa4c-11ea-87e8-5300cd7bee40.jpg)

**Comment by jkeech** [comment]
Hi @PNicolle! Windows Codespaces are in private preview right now, so you'll need to sign up and be accepted into the preview first. Once you are in the preview, you should see the option to create Windows Codespaces from that UI.

Here's where you can sign up: https://visualstudio.microsoft.com/vs/private-preview/

**Comment by PNicolle** [comment]
Hi, jkeech. I already signed up for the private preview and received the mail: "Welcome to the Visual Studio Codespaces Private Preview". So I believe this part is ok...

**Comment by jkeech** [comment]
The email subject has been updated to clarify that you have signed up for the preview rather than making it sound like you are in the preview, so hopefully this doesn't cause the same confusion for other users in the future.

I'm going to go ahead and close this issue since it's expected that you won't be able to create Windows Codespaces until you are in the private preview. Do let us know how it goes once you get access!
