### ISSUE TITLE
Extension vim cannot capture Esc key

### ISSUE THREAD

**Issue by winguse** [MicrosoftDocs/vsonline#59]
Hi,

Nice job on the VSCode Online!

I find extension `vscodevim.vim` cannot capture `Esc` or `Control + [` in the online version (`online.visualstudio.com`). But I am not sure if this is related to the extension itself or actual vscode online.

Thanks!

**Comment by lostintangent** [comment]
@winguse Thanks for reporting this! Are you seeing the `Esc` key work in other contexts of VSO? VSO itself should be handling `Esc` properly, but it's possible there's an issue with the Vim extension. Since I'm not a regular user of the Vim extension, would you be able to provide a simple repro of the issue, so we could investigate it? That would be hugely helpful. Thanks!

**Comment by lostintangent** [comment]
@Chuxel Any thoughts on if/how this could be a problem for Vim? And maybe other extensions?

**Comment by Chuxel** [comment]
Which browser are you using?

Unfortunately, some keys you can't bind because the browser prevents it.  I know ESC was raised as an issue in firefox recently: https://github.com/microsoft/vscode/issues/83566  

//cc: @bpasero @rebornix

**Comment by winguse** [comment]
I am sorry, it seems it's my bad. I cannot reproduce with another clean environment, maybe this is related to my browser's extension.

Thanks for all the responses, and I am closing this issue.
