### ISSUE TITLE
Does VsCode Online have plans to open source code?

### ISSUE THREAD

**Issue by harbin1053020115** [MicrosoftDocs/vsonline#60]
Does VsCode Online have plans to open source code?

**Comment by lostintangent** [comment]
@harbin1053020115 Hey! Right now, we're hyper focused on addressing developer feedback and getting the service to GA (which will require a _lot_ of [work](https://github.com/MicrosoftDocs/vsonline/issues/2)!). Since the codebase will be evolving pretty rapidly, and there's a significant cost to open sourcing a project _correctly_ (e.g. adding good documentation, cleaning up API boundaries, etc.), this isn't something we're currently prioritizing.

That said, this is something we'd love to continue hearing feedback on, as we make progress towards stabilizing the product 👍 In the meantime, I'll close this issue as a question, and we'll make sure to report out any changes in this discussion.

**Comment by Bessonov** [comment]
@lostintangent thank you for your feedback! Will love to see even pre-alpha version. From my point of view it's OK to do it _incorrectly_, i.e. without documentation at all and mark it as an alpha version without any support in the README. Maybe even without allowing to create github issues, until it reach a some defined quality. But yes, if you use internal apis, they need a clear boundaries.

What do you think about it?

**Comment by Bessonov** [comment]
@lostintangent thank you for your feedback! Will love to see even pre-alpha version. From my point of view it's OK to do it _incorrectly_, i.e. without documentation at all and mark it as an alpha version without any support in the README. Maybe even without allowing to create github issues, until it reach a some defined quality. But yes, if you use internal apis, they need a clear boundaries.

What do you think about it?
