### ISSUE TITLE
Enable environment creation for private Azure DevOps repos

### ISSUE THREAD

**Issue by wi5nia** [MicrosoftDocs/vsonline#65]
When can we expect some integration with Azure DevOps? GH integration is super cool but Azure DevOps would also be very useful

**Comment by lostintangent** [comment]
@wi5nia Hey! Just to confirm: are you interested in being able to spin up environments from a private Azure DevOps repo? I just ask, because currently, you can already create environments for any public repo, regardless of the code host. But, we only support private GitHub repos.

We plan to add support for Azure DevOps as well, so we'll use this issue to track it. Thanks!

**Comment by wi5nia** [comment]
I was talking about private Azure DevOps organizations. I can imagine a situation like working from home, I don't have my work computer and I need to make a change so i can just go into Azure DevOps project, click open in VSO and I can keep on working.

**Comment by lostintangent** [comment]
@wi5nia Great! Thanks for confirming that. This is definitely on our near-term roadmap, so I appreciate you sharing the feedback. In the meantime, if you want, you could create an empty environment and then clone your private repo within the environment. It isn't as smooth as we'd like it to be, but it could unblock you for now. Let us know if that solution works!

**Comment by jkeech** [comment]
Azure DevOps support has been shipped! 🚀 This should work both from the web and VS Code desktop. In the web, you will be prompted through an OAuth flow to authorize access to your DevOps account/org the first time you create an environment from an Azure DevOps repo url.
