### ISSUE TITLE
VSO: Visual Studio Online extension always says 'reload required'

### ISSUE THREAD

**Issue by mjbvz** [MicrosoftDocs/vsonline#84]
**Repo**
1. Create a new environment
1. Open in VSO
1. Go to extensions view

**Bug**
Notice that the `Visual Studio Online` extension always says `reload required`

![Screen Shot 2019-11-05 at 3 48 47 PM](https://user-images.githubusercontent.com/12821956/68256069-deac3e80-ffe3-11e9-9721-4fef697d28a8.png)

Reloading does not make this error go away

**Comment by osortega** [comment]
Hi @mjbvz 

Just to clarify, is this just happening when connecting from the browser?

**Comment by lostintangent** [comment]
@osortega Isn't this because the "kitchensink" image doesn't have the newest version of the VS Code extension installed on it? Now that the extension is published to the marketplace, I'm guessing we should remove the VSO extension from the image entirely, and simply install it directly from the marketplace when creating a new environment.

**Comment by osortega** [comment]
@lostintangent you are right, we should do that. I'll do that change.

The only thing I'm wondering is why the "Reload Required" does not go away after reload.

**Comment by jkeech** [comment]
This should be fixed now that we always pull the version from the marketplace instead of keeping a copy in the image.
