### ISSUE TITLE
Web: Placeholder text for repo is confusing

### ISSUE THREAD

**Issue by srivatsn** [MicrosoftDocs/vsonline#91]
From an internal report:

> I saw the that repo field in the create environment form had "microsoft/vsonline-quickstart" and created and environment but only found a Readme.md in the repo.

The placeholder text is maybe too bold and makes it look like the text field is already filled out.

**Comment by nikmd23** [comment]
My 2¢:

I'm not sure if making the placeholders any lighter will solve the problem. [User experience research](https://www.nngroup.com/articles/form-design-placeholders/) strongly suggests that users have difficulty understanding placeholder text.

I suggest we move away from placeholder text, unless we're using it to describe a default value. Here's what I propose the default form would look like going forward:

![image](https://user-images.githubusercontent.com/199026/68442528-45c22280-019f-11ea-8956-0e6acad7c555.png)

- Placeholder removed from name, source repo and dotfiles repo.
- The <optional> tag removed from the target path field (it's already marked optional because it doesn't have the red *)
- If we want/need *instructive text*, we could use one of these patterns: 
![image](https://user-images.githubusercontent.com/199026/68442656-aea99a80-019f-11ea-8f74-dbe0d5d9869f.png)

**Comment by jkeech** [comment]
This change has been deployed.
