### ISSUE TITLE
Extensions that require reload do not correctly install until suspend/unsuspend

### ISSUE THREAD

**Issue by bnb** [MicrosoftDocs/vsonline#95]
Yesterday I was curious about trying out Live Share Audio with VS Online. Did everything I'd expect to do, but it wasn't showing up how it should despite installing and clicking the "reload required" button and having the UI reload. Later in the day, I connected to the machine after it had been suspended and it was appearing as I'd expect it to.

Today, I saw https://github.com/MicrosoftDocs/vsonline/issues/46 and I was guessing that it was the same issue. To test, I spun up a fresh environment using a rust repo (https://github.com/dapr/rust-sdk) and installed the RLS, had the exact same problem – reload required, did it, it didn't work. Suspended the machine and unsuspended, and it worked.

Here's the exact steps I followed with RLS:
<details>
<ul>
  <li>Install RLS</li> 
  <li>Install Rustup</li> 
  <li>(Optional?) Restart the bash terminal</li> 
  <li>(Optional?) run the source $HOME/.cargo/env command rustup tells you to run</li> 
  <li>Suspend the environment</li> 
  <li>Unsuspend the environment</li> 
  <li>There will be a notification that says "RLS not installed. Install?" (paraphrased)</li> 
  <li>Click install and it will be installed.</li>
</ul>
</details>

There is seemingly some kind of disconnect where "Reload Required" is not doing whatever is necessary for the extensions that need it.

**Comment by jkeech** [comment]
The issue here is that the extensions running inside the VS Code server process expect some environment variables to be set. But the VS Code server process was already running before those variables were set system-wide, so they won't take effect until the next time the VS Code server process is restarted. If you were to open a new terminal in VS Code, you should see the variables take effect immediately, but anything in the VS Code process would not see them until after the restart. Suspend + Connect is a good way to force the process restart. Any future usage of the environment should continue to have the correct environment variables set, so it's just an issue for first-time bootstrapping.

The best solution to this will be when we support custom images and/or Dockerfiles. In this case, you could pre-configure the correct environment variables so they are set even before the VS Code server is launched the first time.

**Comment by bnb** [comment]
Would it bee at all possible to detect that the first time bootstrap does not have the correct environment variables and suggest the user open up a new terminal?

**Comment by lostintangent** [comment]
Is there anything we could collaborate on with the VS Code team to improve this experience?

// CC @Chuxel

**Comment by Chuxel** [comment]
@lostintangent What happens for Remote - Containers is that the server is restarted when the container is bounced, so this does not happen.  VS Code Server does not manage these env vars. What might be good to do in these cases is ask if VS Code Server should be restarted so they take effect globally.

**Comment by jkeech** [comment]
@Chuxel, this same behavior should happen in remote-containers. If you install an extension that ends up running a command that sets an env variable, it’s not going to do anything to restart the container, right? So the user is left with the same experience of things not working until they end up restarting.

**Comment by Chuxel** [comment]
@jkeech True - interesting that we haven't heard about this there, but it may be because of remoteEnv and the fact that there's a Rust container.  It's possible some things are just not showing up because of the 54+ pre-config'd definitions.

Interestingly, even locally a reload is not enough if you have multiple windows open... you'd need to shut down all of them for a global env var to kick in.

We might need a "restart server" command or something like that.  Having reload always restart has perf impacts - this is a bit of an exception scenario, so I'd worry about slowing down the primary path with something like this.  There's no great way to detect this scenario that I can think of off hand.

**Comment by Chuxel** [comment]
/cc: @chrmarti in case he has any ideas

**Comment by chrmarti** [comment]
Is the extension setting the environment variables? Where are they set?

A resolver can add environment variables to the remote extension host with the `extensionHostEnv` property in its result. That also works when the server is already running.

**Comment by Chuxel** [comment]
@chrmarti That was my initially impression too - in this case, it sounds like rustup modified OS environment variables. So, the VSO extension is not even aware of the change - nor really is the Rust extension.  The parent process wouldn't know about the change which is what VS Code server is running in.  The only way I can think of this working is to create a new process that the server would run inside (or attempt to source those files which brings risk).

**Comment by chrmarti** [comment]
Restarting the server might be the best and maybe only option then. Detecting the change to the OS files (profile?) could help in notifying the user that something has changed. Not sure if that would yield too many false positives.

**Comment by jkeech** [comment]
We've added a new command "Codespaces: Kill VS Code Server on Host..." which mirrors the functionality of some of the other VS Code Remote extensions. This will allow you to get a fresh VS Code server process on reload without having to first suspend + resume the environment.
